### PR TITLE
Ohh noes price suggestion

### PR DESCRIPTION
**Pull request by JordyMoos**
- [x] Add some fancy code
- [x] Refactor the algorithm list to use constants
- [ ] ~~Make sure all constants get an unique description (to be used as dropdown name)~~
- [ ] ~~Create readme~~
- [ ] ~~Test a lot~~

### CODE REVIEW

**Comment by JordyMoos** [comment]
Giving the algorithm a name does not sound like a job for this addon.
I think a list of the constants and info in the readme will be enough

**Comment by JordyMoos** [comment]
Dropped the readme because it is not needed at this stage.
Also testing can be done in master FTW so ready to merge.

Is this what you intended @marcusklaas

The result of the api will be something like this:

``` lua
{
    hasPrice = bool,
    saleCount = int, -- Total count
    lastSaleTimestamp = int,
    suggestedPriceForGuild = {
        "Guild A" = {
            saleCount = int,
            pricePerUnit = int,
        },
        "Guild B" = {
            -- Etc
        },
    }
    bestPrice = {
        guildName = "Name of best guild to sell to",
        pricePerUnit = int, -- Is already in the suggested list offcourse but its a handy value here
    },
}
```

**Comment by marcusklaas** [comment]
Looks good!

**Comment by JordyMoos** [comment]
Just hit merge ;D

**Pull request merged**
